export const ROUTES = {
  HOME: '/',
  NUTRICION: '/atencion-primaria',
  NUTRICION_ARTICULO: '/atencion-primaria/:slug',
  ACTIVIDAD_FISICA: '/vacunacion',
  ACTIVIDAD_FISICA_ARTICULO: '/vacunacion/:slug',
  SALUD_MENTAL: '/salud-mental',
  SALUD_MENTAL_ARTICULO: '/salud-mental/:slug',
  PREVENCION: '/emergencias',
  PREVENCION_ARTICULO: '/emergencias/:slug',
  BIBLIOTECA: '/biblioteca',
  NOTICIAS: '/noticias',
  NOTICIA: '/noticias/:id',
  CONTACTO: '/contacto',
  NOSOTROS: '/nosotros',
  ADMIN: '/admin',
  ADMIN_ARTICULOS: '/admin/articulos',
  ADMIN_NOTICIAS: '/admin/noticias',
  ADMIN_RECURSOS: '/admin/recursos',
  ADMIN_FAQS: '/admin/faqs',
  ADMIN_MENSAJES: '/admin/mensajes',
  ADMIN_LOGIN: '/admin/login',
  ACCESIBILIDAD: '/accesibilidad',
}

export const NAV_ITEMS = [
  { label: 'Inicio',            path: ROUTES.HOME },
  { label: 'Atención Primaria', path: ROUTES.NUTRICION },
  { label: 'Vacunación',        path: ROUTES.ACTIVIDAD_FISICA },
  { label: 'Salud Mental',      path: ROUTES.SALUD_MENTAL },
  { label: 'Emergencias',       path: ROUTES.PREVENCION },
  { label: 'Biblioteca',        path: ROUTES.BIBLIOTECA },
  { label: 'Noticias',          path: ROUTES.NOTICIAS },
]
